// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: add.proto

#ifndef PROTOBUF_add_2eproto__INCLUDED
#define PROTOBUF_add_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "head.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_add_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsAddImpl();
void InitDefaultsAdd();
inline void InitDefaults() {
  InitDefaultsAdd();
}
}  // namespace protobuf_add_2eproto
namespace hanplayer {
class Add;
class AddDefaultTypeInternal;
extern AddDefaultTypeInternal _Add_default_instance_;
}  // namespace hanplayer
namespace hanplayer {

// ===================================================================

class Add : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hanplayer.Add) */ {
 public:
  Add();
  virtual ~Add();

  Add(const Add& from);

  inline Add& operator=(const Add& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Add(Add&& from) noexcept
    : Add() {
    *this = ::std::move(from);
  }

  inline Add& operator=(Add&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Add& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Add* internal_default_instance() {
    return reinterpret_cast<const Add*>(
               &_Add_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(Add* other);
  friend void swap(Add& a, Add& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Add* New() const PROTOBUF_FINAL { return New(NULL); }

  Add* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const Add& from);
  void MergeFrom(const Add& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(Add* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .hanplayer.ProtoCmd head = 1;
  bool has_head() const;
  void clear_head();
  static const int kHeadFieldNumber = 1;
  const ::hanplayer::ProtoCmd& head() const;
  ::hanplayer::ProtoCmd* release_head();
  ::hanplayer::ProtoCmd* mutable_head();
  void set_allocated_head(::hanplayer::ProtoCmd* head);

  // int32 num = 2;
  void clear_num();
  static const int kNumFieldNumber = 2;
  ::google::protobuf::int32 num() const;
  void set_num(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:hanplayer.Add)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::hanplayer::ProtoCmd* head_;
  ::google::protobuf::int32 num_;
  mutable int _cached_size_;
  friend struct ::protobuf_add_2eproto::TableStruct;
  friend void ::protobuf_add_2eproto::InitDefaultsAddImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Add

// .hanplayer.ProtoCmd head = 1;
inline bool Add::has_head() const {
  return this != internal_default_instance() && head_ != NULL;
}
inline const ::hanplayer::ProtoCmd& Add::head() const {
  const ::hanplayer::ProtoCmd* p = head_;
  // @@protoc_insertion_point(field_get:hanplayer.Add.head)
  return p != NULL ? *p : *reinterpret_cast<const ::hanplayer::ProtoCmd*>(
      &::hanplayer::_ProtoCmd_default_instance_);
}
inline ::hanplayer::ProtoCmd* Add::release_head() {
  // @@protoc_insertion_point(field_release:hanplayer.Add.head)
  
  ::hanplayer::ProtoCmd* temp = head_;
  head_ = NULL;
  return temp;
}
inline ::hanplayer::ProtoCmd* Add::mutable_head() {
  
  if (head_ == NULL) {
    head_ = new ::hanplayer::ProtoCmd;
  }
  // @@protoc_insertion_point(field_mutable:hanplayer.Add.head)
  return head_;
}
inline void Add::set_allocated_head(::hanplayer::ProtoCmd* head) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(head_);
  }
  if (head) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      head = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, head, submessage_arena);
    }
    
  } else {
    
  }
  head_ = head;
  // @@protoc_insertion_point(field_set_allocated:hanplayer.Add.head)
}

// int32 num = 2;
inline void Add::clear_num() {
  num_ = 0;
}
inline ::google::protobuf::int32 Add::num() const {
  // @@protoc_insertion_point(field_get:hanplayer.Add.num)
  return num_;
}
inline void Add::set_num(::google::protobuf::int32 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:hanplayer.Add.num)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace hanplayer

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_add_2eproto__INCLUDED
