// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: parsehead.proto

#include "parsehead.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace hanplayer {
class ParseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Parse>
      _instance;
} _Parse_default_instance_;
}  // namespace hanplayer
namespace protobuf_parsehead_2eproto {
void InitDefaultsParseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_head_2eproto::InitDefaultsProtoCmd();
  {
    void* ptr = &::hanplayer::_Parse_default_instance_;
    new (ptr) ::hanplayer::Parse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::hanplayer::Parse::InitAsDefaultInstance();
}

void InitDefaultsParse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsParseImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hanplayer::Parse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::hanplayer::Parse, haha_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::hanplayer::Parse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::hanplayer::_Parse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "parsehead.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\017parsehead.proto\022\thanplayer\032\nhead.proto"
      "\"*\n\005Parse\022!\n\004haha\030\001 \001(\0132\023.hanplayer.Prot"
      "oCmdb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 92);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "parsehead.proto", &protobuf_RegisterTypes);
  ::protobuf_head_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_parsehead_2eproto
namespace hanplayer {

// ===================================================================

void Parse::InitAsDefaultInstance() {
  ::hanplayer::_Parse_default_instance_._instance.get_mutable()->haha_ = const_cast< ::hanplayer::ProtoCmd*>(
      ::hanplayer::ProtoCmd::internal_default_instance());
}
void Parse::clear_haha() {
  if (GetArenaNoVirtual() == NULL && haha_ != NULL) {
    delete haha_;
  }
  haha_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Parse::kHahaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Parse::Parse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_parsehead_2eproto::InitDefaultsParse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:hanplayer.Parse)
}
Parse::Parse(const Parse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_haha()) {
    haha_ = new ::hanplayer::ProtoCmd(*from.haha_);
  } else {
    haha_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:hanplayer.Parse)
}

void Parse::SharedCtor() {
  haha_ = NULL;
  _cached_size_ = 0;
}

Parse::~Parse() {
  // @@protoc_insertion_point(destructor:hanplayer.Parse)
  SharedDtor();
}

void Parse::SharedDtor() {
  if (this != internal_default_instance()) delete haha_;
}

void Parse::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Parse::descriptor() {
  ::protobuf_parsehead_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_parsehead_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Parse& Parse::default_instance() {
  ::protobuf_parsehead_2eproto::InitDefaultsParse();
  return *internal_default_instance();
}

Parse* Parse::New(::google::protobuf::Arena* arena) const {
  Parse* n = new Parse;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Parse::Clear() {
// @@protoc_insertion_point(message_clear_start:hanplayer.Parse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && haha_ != NULL) {
    delete haha_;
  }
  haha_ = NULL;
  _internal_metadata_.Clear();
}

bool Parse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hanplayer.Parse)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .hanplayer.ProtoCmd haha = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_haha()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hanplayer.Parse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hanplayer.Parse)
  return false;
#undef DO_
}

void Parse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hanplayer.Parse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .hanplayer.ProtoCmd haha = 1;
  if (this->has_haha()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->haha_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:hanplayer.Parse)
}

::google::protobuf::uint8* Parse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hanplayer.Parse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .hanplayer.ProtoCmd haha = 1;
  if (this->has_haha()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->haha_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:hanplayer.Parse)
  return target;
}

size_t Parse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hanplayer.Parse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .hanplayer.ProtoCmd haha = 1;
  if (this->has_haha()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->haha_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Parse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hanplayer.Parse)
  GOOGLE_DCHECK_NE(&from, this);
  const Parse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Parse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hanplayer.Parse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hanplayer.Parse)
    MergeFrom(*source);
  }
}

void Parse::MergeFrom(const Parse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hanplayer.Parse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_haha()) {
    mutable_haha()->::hanplayer::ProtoCmd::MergeFrom(from.haha());
  }
}

void Parse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hanplayer.Parse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Parse::CopyFrom(const Parse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hanplayer.Parse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Parse::IsInitialized() const {
  return true;
}

void Parse::Swap(Parse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Parse::InternalSwap(Parse* other) {
  using std::swap;
  swap(haha_, other->haha_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Parse::GetMetadata() const {
  protobuf_parsehead_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_parsehead_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace hanplayer

// @@protoc_insertion_point(global_scope)
